---

# UUID d'exécution
# le filtre 'to_uuid' transforme une chaine en UUID mais elle doit changer pour être aléatoire. D'où le 'ansible_date_time'
uuid_execution: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
