---

# Vérification du bon fonctionnement de l'applicatif
#   async+poll : attente de 20 secondes et poll de 5
#   register : création d'une variable "scrout" pour afficher des logs
- name: "[Vérifier] Vérification de l'état de {{ applicatif_nom }}"
  ansible.builtin.command:
    cmd: "{{ applicatifs_rep }}{{ applicatif_nom }}/{{ applicatif_nom }}.sh status"
  async: 120
  poll: 05
  register: "scrout"

- name: "[Vérifier] logs du statut"
  debug: "var=scrout.stdout_lines"
