---

# Description du rôle
galaxy_info:
  author: "Guillaume TALBOT"
  description: "Ce rôle installe se limite à toutes les configurations/actions communes au niveau OS/UNIX"
  min_ansible_version: "2.8"
  license: "This program is offered under a commercial and under the AGPL license. See LICENSE.md in repository root directory"
