---
#
# Pour démarrer le script, exécuter :
#   ansible-playbook ansible/03_deployer.yml -i ansible/inventory/local
#
# Pour se limiter à un groupe de machines, ajouter --limit machines_zone_execution_exposee
# Pour se limiter à un applicatif précis, ajouter --tags socle-securite
#
# Ce script s'exécute sans aucun droit SUDO
#

# Rien à faire pour service-redis

- name: "[03_deployer] Déploiement de l'applicatif service-gateway"
  tags: "service-gateway"
  hosts: "machines_service_gateway"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "service-gateway"
        applicatif_version: "{{ version_service_gateway }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/servicescloud/service-gateway/"

- name: "[03_deployer] Déploiement de l'applicatif service-registry"
  tags: "service-registry"
  hosts: "machines_service_registry"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "service-registry"
        applicatif_version: "{{ version_service_registry }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/servicescloud/service-registry/"

- name: "[03_deployer] Déploiement de l'applicatif service-config"
  tags: "service-config"
  hosts: "machines_service_config"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "service-config"
        applicatif_version: "{{ version_service_config }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/servicescloud/service-config/"

- name: "[03_deployer] Déploiement de l'applicatif service-admin"
  tags: "service-admin"
  hosts: "machines_service_admin"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "service-admin"
        applicatif_version: "{{ version_service_admin }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/servicescloud/service-admin/"

- name: "[03_deployer] Déploiement de l'applicatif service-ldap"
  tags: "service-ldap"
  hosts: "machines_service_ldap"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "service-ldap"
        applicatif_version: "{{ version_service_ldap }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/servicescloud/service-ldap/"

- name: "[03_deployer] Déploiement de l'applicatif service-nosql"
  tags: "service-nosql"
  hosts: "machines_service_nosql"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "service-nosql"
        applicatif_version: "{{ version_service_nosql }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/servicescloud/service-nosql/"

- name: "[03_deployer] Déploiement de l'applicatif socle-dbbrouillon"
  tags: "socle-dbbrouillon"
  hosts: "machines_socle_dbbrouillon"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-dbbrouillon"
        applicatif_version: "{{ version_socle_dbbrouillon }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-dbbrouillon/"

- name: "[03_deployer] Déploiement de l'applicatif socle-dbconfiguration"
  tags: "socle-dbconfiguration"
  hosts: "machines_socle_dbconfiguration"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-dbconfiguration"
        applicatif_version: "{{ version_socle_dbconfiguration }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-dbconfiguration/"

- name: "[03_deployer] Déploiement de l'applicatif socle-dbdocument"
  tags: "socle-dbdocument"
  hosts: "machines_socle_dbdocument"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-dbdocument"
        applicatif_version: "{{ version_socle_dbdocument }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-dbdocument/"

- name: "[03_deployer] Déploiement de l'applicatif socle-dbnotification"
  tags: "socle-dbnotification"
  hosts: "machines_socle_dbnotification"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-dbnotification"
        applicatif_version: "{{ version_socle_dbnotification }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-dbnotification/"

- name: "[03_deployer] Déploiement de l'applicatif socle-referentiel"
  tags: "socle-referentiel"
  hosts: "machines_socle_referentiel"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-referentiel"
        applicatif_version: "{{ version_socle_referentiel }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-referentiel/"

- name: "[03_deployer] Déploiement de l'applicatif socle-referentielexterne"
  tags: "socle-referentielexterne"
  hosts: "machines_socle_referentielexterne"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-referentielexterne"
        applicatif_version: "{{ version_socle_referentielexterne }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-referentielexterne/"

- name: "[03_deployer] Déploiement de l'applicatif socle-securite"
  tags: "socle-securite"
  hosts: "machines_socle_securite"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-securite"
        applicatif_version: "{{ version_socle_securite }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-securite/"

- name: "[03_deployer] Déploiement de l'applicatif socle-soumission"
  tags: "socle-soumission"
  hosts: "machines_socle_soumission"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-soumission"
        applicatif_version: "{{ version_socle_soumission }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-soumission/"

- name: "[03_deployer] Déploiement de l'applicatif socle-transfert"
  tags: "socle-transfert"
  hosts: "machines_socle_transfert"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-transfert"
        applicatif_version: "{{ version_socle_transfert }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-transfert/"

- name: "[03_deployer] Déploiement de l'applicatif socle-adminpsl"
  tags: "socle-adminpsl"
  hosts: "machines_socle_adminpsl"
  roles:
    - role: "commun/ad_deployer_applicatif"
      vars:
        applicatif_nom: "socle-adminpsl"
        applicatif_version: "{{ version_socle_adminpsl }}"
        applicatif_binaire_rep: "{{ binaire_rep }}com/github/talbotgui/psl/socle/socle-adminpsl/"

- name: "[03_deployer] Déploiement de l'applicatif WEB public (front) generique"
  tags: [ "web-front", "generique" ]
  hosts: "machines_web_front"
  roles:
    - role: "commun/aj_deployer_web" 
      vars: { "groupId": "com.github.talbotgui.psl", "artifactId": "front", "version": "{{ version_front.generique }}", "classifier": "generique", "prefix_deploiement": "mademarche/" }

- name: "[03_deployer] Déploiement de l'applicatif WEB public (front) specifique"
  tags: [ "web-front", "specifique" ]
  hosts: "machines_web_front"
  roles:
    - role: "commun/aj_deployer_web" 
      vars: { "groupId": "com.github.talbotgui.psl", "artifactId": "front", "version": "{{ version_front.specifique }}", "classifier": "specifique", "prefix_deploiement": "mademarche/" }

- name: "[03_deployer] Déploiement de l'applicatif WEB d'administration adminpsl"
  tags: [ "web-admin", "adminpsl" ]
  hosts: "machines_web_admin"
  roles:
    - role: "commun/aj_deployer_web" 
      vars: { "groupId": "com.github.talbotgui.psl", "artifactId": "front", "version": "{{ version_front.adminpsl }}", "classifier": "adminpsl", "prefix_deploiement": "mademarche/" }

- name: "[03_deployer] Déploiement de l'applicatif WEB d'administration edition"
  tags: [ "web-admin", "edition" ]
  hosts: "machines_web_admin"
  roles:
    - role: "commun/aj_deployer_web" 
      vars: { "groupId": "com.github.talbotgui.psl", "artifactId": "front", "version": "{{ version_front.edition }}", "classifier": "edition", "prefix_deploiement": "mademarche/" }

- name: "[03_deployer] Déploiement de la documentation"
  tags: [ "web-admin", "documentation" ]
  hosts: "machines_web_admin"
  roles:
    - role: "commun/aj_deployer_web" 
      vars: { "groupId": "com.github.talbotgui.psl", "artifactId": "documentation", "version": "{{ version_front.documentation }}", "classifier": "documentation", "prefix_deploiement": "" }
