# Ce fichier de l'inventaire décrit le plan de déploiement et donc la répartition des applicatifs sur les différentes machines logiques.
#
all:

  children:

    ############################
    # Groupe par service déployé (cette partie correspond au plan de déploiement)
    ############################
    machines_web_front: { hosts: { "EXE_EXP_[1:3]": } }
    machines_web_admin: { hosts: { "ADM_INT_[1:3]": } }

    machines_service_redis: { hosts: { "EXE_PRO_[1:3]": } }
    machines_service_gateway: { hosts: { "EXE_EXP_[1:3]": } }
    machines_service_registry: { hosts: { "EXE_PRO_[1:3]": } }
    machines_service_config: { hosts: { "ADM_INT_[1:2]": } }
    machines_service_admin: { hosts: { "ADM_INT_[1:2]": } }
    machines_service_ldap: { hosts: { "ADM_PRO_[1:3]": } }
    machines_service_nosql: { hosts: { "EXE_PRO_[1:3]": } }

    machines_socle_dbbrouillon: { hosts: { "EXE_INT_[1:3]": } }
    machines_socle_dbconfiguration: { hosts: { "EXE_INT_[1:3]": } }
    machines_socle_dbdocument: { hosts: { "EXE_INT_[1:3]": } }
    machines_socle_dbnotification: { hosts: { "EXE_INT_[1:3]": } }
    machines_socle_referentiel: { hosts: { "EXE_INT_[1:3]": } }
    machines_socle_referentielexterne: { hosts: { "EXE_INT_[1:3]": } }
    machines_socle_securite: { hosts: { "EXE_PRO_[1:3]": } }
    machines_socle_soumission: { hosts: { "EXE_INT_[1:3]": } }
    machines_socle_transfert: { hosts: { "ADM_INT_[1:2]": } }
    machines_socle_adminpsl: { hosts: { "ADM_INT_[1:2]": } }
